#!/usr/bin/env bash
# gives you information about the holbertonschool file

FILE="school"
if [ -e "$FILE" ]; then
    echo "$FILE file exists"
    if [ -s "$FILE" ]; then
	echo "file is not empty"
    else
	echo "file is empty"
    fi
    if [ -f "$FILE" ]; then
	echo "file is a regular file"
    fi
else
    echo "file does not exist"
fi
